  
baseURL = "http://example.org/"
languageCode = "en-us"
title = "Freakston"
theme = "hugo-ink"
paginate = 5

copyright = "©Freakston Copyright notice"

pygmentsstyle = "vs"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

[params]
	subtitle = "やめてください [Twitter](https://twitter.com/Freakst0n)"

	# Optional 64x64 avatar image.
	avatar = "favc.png"
	
    featherIconsCDN = true

	mode = "dark" # "dark" or "auto"

# Nav.
[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "All posts"
url = "/posts"
weight = 2

[[menu.main]]
name = "About"
url = "/about"
weight = 3

[[params.social]]
name = "Github"
icon = "github"
url = "https://github.com/Freakston"

[[params.social]]
name = "RSS"
icon = "rss"
url = "/index.xml"

[taxonomies]
   tag = "tags"
