baseURL = "/"
languageCode = "en-us"
title = "Freakston"
theme = "hugo-ink"
copyright = "©Freakston"

# Modern syntax highlighting (replaces pygments*)
[markup]
  [markup.highlight]
    style = "vs"
    lineNos = false
    codeFences = true
    guessSyntax = true

[params]
  subtitle = "ようこそ [Twitter](https://twitter.com/Freakst0n)"
  # Optional 64x64 avatar image.
  avatar = "favc.png"
  featherIconsCDN = true
  mode = "dark" # "dark" or "auto"

# Nav.
[[menu.main]]
  name = "Home"
  url = "/"
  weight = 1

[[menu.main]]
  name = "All posts"
  url = "/posts"
  weight = 2

[[menu.main]]
  name = "About"
  url = "/about"
  weight = 3

[[menu.main]]
  name = "Resume"
  url = "Resume.pdf"
  weight = 4

[[params.social]]
  name = "Github"
  icon = "github"
  url = "https://github.com/Freakston"

[[params.social]]
  name = "RSS"
  icon = "rss"
  url = "/index.xml"

[taxonomies]
  tag = "tags"
  category = "categories"
